# Generated by Django 5.2.8 on 2025-12-29 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the grading scale (e.g., CBC, Standard)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_scales', to='classes.school')),
            ],
            options={
                'verbose_name': 'Grading Scale',
                'verbose_name_plural': 'Grading Scales',
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='grading_scale',
            field=models.ForeignKey(blank=True, help_text='The grading scale used for this subject', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='classes.gradingscale'),
        ),
        migrations.CreateModel(
            name='GradingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Exceeding Expectation', max_length=100)),
                ('abbreviation', models.CharField(blank=True, help_text='e.g., EE, ME, AE, BE', max_length=10)),
                ('min_score', models.DecimalField(decimal_places=2, help_text='Minimum percentage for this level (0-100)', max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Maximum percentage for this level (0-100)', max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='classes.gradingscale')),
            ],
            options={
                'verbose_name': 'Grading Level',
                'verbose_name_plural': 'Grading Levels',
                'ordering': ['-min_score'],
                'unique_together': {('scale', 'name')},
            },
        ),
    ]
